### ISSUE TITLE
Suggestions and showcase

### ISSUE THREAD

**Issue by DesdeChaves** [FeatherCMS/feather#43]
**Showcase:**
My first FEAHER CMS runs at http://gravato.aejm.pt (is still in the process of customization). Thanks to all.

**Suggestions:**

- I need to translate "AUTHOR" to "Autor" in the post page: it would be great to have a variable for that.
- the News module should be installed "out of the box".
- a nice module for writing  formulas and equations.

**Doubts:**

- What is the best approach to include more figures in the posts?
- How can change "Read Now" to "Ler agora"?
- I added a new category "Liderança" that is not listed in the page Categories. What I'm missing?

Happy New Year to all.

**Comment by tib** [comment]
Hey,

- There is a WIP translation [Leaf entity](https://github.com/FeatherCMS/feather-core/blob/main/Sources/FeatherCore/Leaf/TranslationLeafEntity.swift) in the FeatherCore framework, but it's not ready yet. Unfortunately I had no time to focus on a proper translation API, but ideally every module should return a translation dictionary (using hooks) and translate text blocks in leaf using a "authors".t() method or similar. [need-help]
- The best practice is to fork this repository and add the required modules. Of course later on we can add more modules, but this repository only functions as a "sample" configuration. Which news module are you referring to exactly (aggregator)?
- You can create a content filter to achieve this kind of functionality, it's really straightforward, you can check the [markdown](https://github.com/FeatherCMS/markdown-module/blob/main/Sources/MarkdownModule/ContentFilters/MarkdownFilter.swift) or the [swifty](https://github.com/FeatherCMS/swifty-module/blob/main/Sources/SwiftyModule/ContentFilters/SwiftyFilter.swift) module for reference, docs are in the works... 
- What kind of figures are you referring to? Images? Unfortunately you have to use markdown or raw HTML for now, I'm working on a visual editor but had zero time to build it. [need-help] 
- You can customise all of your templates by overriding them inside the Resources folder. The system will use those templates instead of the bundled ones, that's how you can build custom themes for your site. If you remove something from the Resources folder Feather will copy the missing item on the next start, in other words the default template will be restored. I'd suggest to commit the entire Resources folder to your own repository or just the altered template files, this way you can maintain your own design.
- Authors, categories and blog posts are content types with an associated metadata item. This means that they will only appear on the frontend if you publish them. You can do this under the edit page by clicking the Feather icon and set the status to Published. I'll create a comprehensive user guide, also you can read about [metadatas](https://github.com/FeatherCMS/feather/wiki/Project-structure#frontend-metadata-interface) in the wiki.

Thank you very much for these feedbacks. 🙏
